INSERT INTO user_role
    (user_role_id, description, role_name, is_default)
VALUES (1, 'Default role', 'USER', true),
       (2, 'God of server role likes root', 'ADMIN', false);

INSERT INTO category
    (category_id, description, name, type, is_default)
VALUES (1, 'Good expense', 'Food', 0, true),
       (2, 'Here comes the money', 'Salary', 1, true),
       (3, 'To get or receive something from someone with the intention of giving it back after a period of time',
        'Borrow', 2, true),
       (4, 'An act of lending something', 'Loan', 3, true),
       (5, 'Return borrowed item', 'Borrow back', 4, true),
       (6, 'Receiving the loan', 'Loan back', 5, true),
       (7, 'Entertainment', 'Entertainment', 0, true),
       (8, 'Everybody like getting presents', 'Present', 1, true);
INSERT INTO user_item_key

    (user_item_key_id, name)
VALUES (1, 'favoriteWalletId');

INSERT INTO currency
    (currency_id, code, currency, state_or_territory, symbol)
VALUES (1, '', 'Abkhazian apsar[E]', ' Abkhazia', ''),
       (2, 'RUB', 'Russian ruble', ' Abkhazia', ''),
       (3, 'AFN', 'Afghan afghani', ' Afghanistan', ''),
       (4, 'EUR', 'Euro', ' Akrotiri and Dhekelia', '€'),
       (5, 'ALL', 'Albanian lek', ' Albania', 'L'),
       (6, '', 'Alderney pound[E]', ' Alderney', ''),
       (7, 'GBP', 'British pound[F]', ' Alderney', ''),
       (8, 'GGP[G]', 'Guernsey pound', ' Alderney', ''),
       (9, 'DZD', 'Algerian dinar', ' Algeria', ''),
       (10, 'EUR', 'Euro', ' Andorra', '€'),
       (11, 'AOA', 'Angolan kwanza', ' Angola', 'Kz'),
       (12, 'XCD', 'Eastern Caribbean dollar', ' Anguilla', '$'),
       (13, 'XCD', 'Eastern Caribbean dollar', ' Antigua and Barbuda', '$'),
       (14, 'ARS', 'Argentine peso', ' Argentina', '$'),
       (15, 'AMD', 'Armenian dram', ' Armenia', ''),
       (16, '', 'Artsakh dram[E]', ' Artsakh', ''),
       (17, 'AMD', 'Armenian dram', ' Artsakh', ''),
       (18, 'AWG', 'Aruban florin', ' Aruba', ''),
       (19, 'SHP', 'Saint Helena pound', 'United KingdomAscension Island', ''),
       (20, 'AUD', 'Australian dollar', ' Australia', '$'),
       (21, 'EUR', 'Euro', ' Austria', '€'),
       (22, 'AZN', 'Azerbaijani manat', ' Azerbaijan', ''),
       (23, 'BSD', 'Bahamian dollar', ' Bahamas, The', '$'),
       (24, 'BHD', 'Bahraini dinar', ' Bahrain', ''),
       (25, 'BDT', 'Bangladeshi taka', ' Bangladesh', ''),
       (26, 'BBD', 'Barbadian dollar', ' Barbados', '$'),
       (27, 'BYN', 'Belarusian ruble', ' Belarus', 'Br'),
       (28, 'EUR', 'Euro', ' Belgium', '€'),
       (29, 'BZD', 'Belize dollar', ' Belize', '$'),
       (30, 'XOF', 'West African CFA franc', ' Benin', 'Fr'),
       (31, 'BMD', 'Bermudian dollar', ' Bermuda', '$'),
       (32, 'BTN', 'Bhutanese ngultrum', ' Bhutan', 'Nu.'),
       (33, 'INR', 'Indian rupee', ' Bhutan', ''),
       (34, 'BOB', 'Bolivian boliviano', ' Bolivia', 'Bs.'),
       (35, 'USD', 'United States dollar[H]', ' Bonaire', '$'),
       (36, 'BAM', 'Bosnia and Herzegovina convertible mark', ' Bosnia and Herzegovina', 'KM or ??[I]'),
       (37, 'BWP', 'Botswana pula', ' Botswana', 'P'),
       (38, 'BRL', 'Brazilian real', ' Brazil', 'R$'),
       (39, 'USD', 'United States dollar', ' British Indian Ocean Territory', '$'),
       (40, 'USD', 'United States dollar', ' British Virgin Islands', '$'),
       (41, 'BND', 'Brunei dollar', ' Brunei', '$'),
       (42, 'SGD', 'Singapore dollar', ' Brunei', '$'),
       (43, 'BGN', 'Bulgarian lev', ' Bulgaria', '??.'),
       (44, 'XOF', 'West African CFA franc', ' Burkina Faso', 'Fr'),
       (45, 'BIF', 'Burundian franc', ' Burundi', 'Fr'),
       (46, 'KHR', 'Cambodian riel', ' Cambodia', ''),
       (47, 'XAF', 'Central African CFA franc', ' Cameroon', 'Fr'),
       (48, 'CAD', 'Canadian dollar', ' Canada', '$'),
       (49, 'CVE', 'Cape Verdean escudo', ' Cape Verde', '$'),
       (50, 'KYD', 'Cayman Islands dollar', ' Cayman Islands', '$'),
       (51, 'XAF', 'Central African CFA franc', ' Central African Republic', 'Fr'),
       (52, 'XAF', 'Central African CFA franc', ' Chad', 'Fr'),
       (53, 'CLP', 'Chilean peso', ' Chile', '$'),
       (54, 'CNY', 'Renminbi/Chinese yuan', ' China, People\'s Republic of', ''),
       (55, 'COP', 'Colombian peso', ' Colombia', '$'),
       (56, 'KMF', 'Comorian franc', ' Comoros', 'Fr'),
       (57, 'CDF', 'Congolese franc', ' Congo, Democratic Republic of the', 'Fr'),
       (58, 'XAF', 'Central African CFA franc', ' Congo, Republic of the', 'Fr'),
       (59, 'CKD[G]', 'Cook Islands dollar', ' Cook Islands', '$'),
       (60, 'NZD', 'New Zealand dollar', ' Cook Islands', '$'),
       (61, 'CRC', 'Costa Rican colón', ' Costa Rica', ''),
       (62, 'XOF', 'West African CFA franc', ' Côte d\'Ivoire', 'Fr'),
       (63, 'HRK', 'Croatian kuna', ' Croatia', 'kn'),
       (64, 'CUP', 'Cuban peso', ' Cuba', '$'),
       (65, 'CUC', 'Cuban convertible peso', ' Cuba', 'CUC$'),
       (66, 'ANG', 'Netherlands Antillean guilder', ' Curaçao', ''),
       (67, 'EUR', 'Euro', ' Cyprus', '€'),
       (68, 'CZK', 'Czech koruna', ' Czech Republic', 'Kč'),
       (69, 'DKK', 'Danish krone', ' Denmark', 'kr'),
       (70, 'DJF', 'Djiboutian franc', ' Djibouti', 'Fr'),
       (71, 'XCD', 'Eastern Caribbean dollar', ' Dominica', '$'),
       (72, 'DOP', 'Dominican peso', ' Dominican Republic', 'RD$'),
       (73, 'USD', 'United States dollar', ' East Timor', '$'),
       (74, '', '', ' East Timor', ''),
       (75, 'USD', 'United States dollar', ' Ecuador', '$'),
       (76, '', '', ' Ecuador', ''),
       (77, 'EGP', 'Egyptian pound', ' Egypt', '? or ?.?'),
       (78, 'USD', 'United States dollar', ' El Salvador', '$'),
       (79, '(none, BTC and XBT used in practice)', 'Bitcoin[5]', ' El Salvador', ''),
       (80, 'XAF', 'Central African CFA franc', ' Equatorial Guinea', 'Fr'),
       (81, 'ERN', 'Eritrean nakfa', ' Eritrea', 'Nfk'),
       (82, 'EUR', 'Euro', ' Estonia', '€'),
       (83, 'SZL', 'Swazi lilangeni', ' Eswatini', 'L'),
       (84, 'ZAR', 'South African rand', ' Eswatini', 'R'),
       (85, 'ETB', 'Ethiopian birr', ' Ethiopia', 'Br'),
       (86, 'FKP', 'Falkland Islands pound', ' Falkland Islands', ''),
       (87, 'DKK', 'Danish krone', ' Faroe Islands', 'kr'),
       (88, 'FOK[G]', 'Faroese króna', ' Faroe Islands', 'kr'),
       (89, 'FJD', 'Fijian dollar', ' Fiji', '$'),
       (90, 'EUR', 'Euro', ' Finland', '€'),
       (91, 'EUR', 'Euro', ' France', '€'),
       (92, 'XPF', 'CFP franc', ' French Polynesia', ''),
       (93, 'XAF', 'Central African CFA franc', ' Gabon', 'Fr'),
       (94, 'GMD', 'Gambian dalasi', ' Gambia, The', 'D'),
       (95, 'GEL', 'Georgian lari', ' Georgia', ''),
       (96, 'EUR', 'Euro', ' Germany', '€'),
       (97, 'GHS', 'Ghanaian cedi', ' Ghana', ''),
       (98, 'GIP', 'Gibraltar pound', ' Gibraltar', ''),
       (99, 'EUR', 'Euro', ' Greece', '€'),
       (100, 'DKK', 'Danish krone', ' Greenland', 'kr'),
       (101, 'XCD', 'Eastern Caribbean dollar', ' Grenada', '$'),
       (102, 'GTQ', 'Guatemalan quetzal', ' Guatemala', 'Q'),
       (103, 'GGP[G]', 'Guernsey pound', ' Guernsey', ''),
       (104, 'GBP', 'British pound[F]', ' Guernsey', ''),
       (105, 'GNF', 'Guinean franc', ' Guinea', 'Fr'),
       (106, 'XOF', 'West African CFA franc', ' Guinea-Bissau', 'Fr'),
       (107, 'GYD', 'Guyanese dollar', ' Guyana', '$'),
       (108, 'HTG', 'Haitian gourde', ' Haiti', 'G'),
       (109, 'HNL', 'Honduran lempira', ' Honduras', 'L'),
       (110, 'HKD', 'Hong Kong dollar', ' Hong Kong', '$'),
       (111, 'HUF', 'Hungarian forint', ' Hungary', 'Ft'),
       (112, 'ISK', 'Icelandic króna', ' Iceland', 'kr'),
       (113, 'INR', 'Indian rupee', ' India', ''),
       (114, 'IDR', 'Indonesian rupiah', ' Indonesia', 'Rp'),
       (115, 'IRR', 'Iranian rial', ' Iran', ''),
       (116, 'IQD', 'Iraqi dinar', ' Iraq', ''),
       (117, 'EUR', 'Euro', ' Ireland', '€'),
       (118, 'IMP[G]', 'Manx pound', ' Isle of Man', ''),
       (119, 'GBP', 'British pound[F]', ' Isle of Man', ''),
       (120, 'ILS', 'Israeli new shekel', ' Israel', ''),
       (121, 'EUR', 'Euro', ' Italy', '€'),
       (122, 'JMD', 'Jamaican dollar', ' Jamaica', '$'),
       (123, 'JPY', 'Japanese yen', ' Japan', '? or ?'),
       (124, 'JEP[G]', 'Jersey pound', ' Jersey', ''),
       (125, 'GBP', 'British pound[F]', ' Jersey', ''),
       (126, 'JOD', 'Jordanian dinar', ' Jordan', ''),
       (127, 'KZT', 'Kazakhstani tenge', ' Kazakhstan', ''),
       (128, 'KES', 'Kenyan shilling', ' Kenya', 'Sh'),
       (129, 'KID[G]', 'Kiribati dollar[E]', ' Kiribati', '$'),
       (130, 'AUD', 'Australian dollar', ' Kiribati', '$'),
       (131, 'KPW', 'North Korean won', ' Korea, North', ''),
       (132, 'KRW', 'South Korean won', ' Korea, South', ''),
       (133, 'EUR', 'Euro', ' Kosovo', '€'),
       (134, 'KWD', 'Kuwaiti dinar', ' Kuwait', ''),
       (135, 'KGS', 'Kyrgyz som', ' Kyrgyzstan', ''),
       (136, 'LAK', 'Lao kip', ' Laos', ''),
       (137, 'EUR', 'Euro', ' Latvia', '€'),
       (138, 'LBP', 'Lebanese pound', ' Lebanon', ''),
       (139, 'LSL', 'Lesotho loti', ' Lesotho', 'L'),
       (140, 'ZAR', 'South African rand', ' Lesotho', 'R'),
       (141, 'LRD', 'Liberian dollar', ' Liberia', '$'),
       (142, 'LYD', 'Libyan dinar', ' Libya', ''),
       (143, 'CHF', 'Swiss franc', ' Liechtenstein', 'Fr.'),
       (144, 'EUR', 'Euro', ' Lithuania', '€'),
       (145, 'EUR', 'Euro', ' Luxembourg', '€'),
       (146, 'MOP', 'Macanese pataca', ' Macau', 'MOP$'),
       (147, 'HKD', 'Hong Kong dollar', ' Macau', '$'),
       (148, 'MGA', 'Malagasy ariary', ' Madagascar', 'Ar'),
       (149, 'MWK', 'Malawian kwacha', ' Malawi', 'MK'),
       (150, 'MYR', 'Malaysian ringgit', ' Malaysia', 'RM'),
       (151, 'MVR', 'Maldivian rufiyaa', ' Maldives', '.?'),
       (152, 'XOF', 'West African CFA franc', ' Mali', 'Fr'),
       (153, 'EUR', 'Euro', ' Malta', '€'),
       (154, 'USD', 'United States dollar', ' Marshall Islands', '$'),
       (155, 'MRU', 'Mauritanian ouguiya', ' Mauritania', 'UM'),
       (156, 'MUR', 'Mauritian rupee', ' Mauritius', ''),
       (157, 'MXN', 'Mexican peso', ' Mexico', '$'),
       (158, 'USD', 'United States dollar', ' Micronesia', '$'),
       (159, 'MDL', 'Moldovan leu', ' Moldova', 'L'),
       (160, 'EUR', 'Euro', ' Monaco', '€'),
       (161, 'MNT', 'Mongolian tögrög', ' Mongolia', ''),
       (162, 'EUR', 'Euro', ' Montenegro', '€'),
       (163, 'XCD', 'Eastern Caribbean dollar', ' Montserrat', '$'),
       (164, 'MAD', 'Moroccan dirham', ' Morocco', '?.?.'),
       (165, 'MZN', 'Mozambican metical', ' Mozambique', 'MT'),
       (166, 'MMK', 'Burmese kyat', ' Myanmar', 'Ks'),
       (167, 'NAD', 'Namibian dollar', ' Namibia', '$'),
       (168, 'ZAR', 'South African rand', ' Namibia', 'R'),
       (169, 'AUD', 'Australian dollar', ' Nauru', '$'),
       (170, 'NPR', 'Nepalese rupee', '   Nepal', ''),
       (171, 'EUR', 'Euro', ' Netherlands[H]', '€'),
       (172, 'XPF', 'CFP franc', ' New Caledonia', ''),
       (173, 'NZD', 'New Zealand dollar', ' New Zealand', '$'),
       (174, 'NIO', 'Nicaraguan córdoba', ' Nicaragua', 'C$'),
       (175, 'XOF', 'West African CFA franc', ' Niger', 'Fr'),
       (176, 'NGN', 'Nigerian naira', ' Nigeria', ''),
       (177, 'NZD', 'New Zealand dollar', ' Niue', '$'),
       (178, '', 'Niue dollar[E]', ' Niue', '$'),
       (179, 'MKD', 'Macedonian denar', ' North Macedonia', ''),
       (180, 'TRY', 'Turkish lira', ' Northern Cyprus', ''),
       (181, 'NOK', 'Norwegian krone', ' Norway', 'kr'),
       (182, 'OMR', 'Omani rial', ' Oman', ''),
       (183, 'PKR', 'Pakistani rupee', ' Pakistan', ''),
       (184, 'USD', 'United States dollar', ' Palau', '$'),
       (185, 'ILS', 'Israeli new shekel', ' Palestine', ''),
       (186, 'JOD', 'Jordanian dinar', ' Palestine', ''),
       (187, 'PAB', 'Panamanian balboa', ' Panama', 'B/.'),
       (188, 'USD', 'United States dollar', ' Panama', '$'),
       (189, 'PGK', 'Papua New Guinean kina', ' Papua New Guinea', 'K'),
       (190, 'PYG', 'Paraguayan guaraní', ' Paraguay', ''),
       (191, 'PEN', 'Peruvian sol', ' Peru', 'S/.'),
       (192, 'PHP', 'Philippine peso', ' Philippines', ''),
       (193, 'NZD', 'New Zealand dollar', ' Pitcairn Islands', '$'),
       (194, 'PND[G]', 'Pitcairn Islands dollar[E]', ' Pitcairn Islands', '$'),
       (195, 'PLN', 'Polish złoty', ' Poland', 'zł'),
       (196, 'EUR', 'Euro', ' Portugal', '€'),
       (197, 'QAR', 'Qatari riyal', ' Qatar', ''),
       (198, 'RON', 'Romanian leu', ' Romania', 'lei'),
       (199, 'RUB', 'Russian ruble', ' Russia', ''),
       (200, 'RWF', 'Rwandan franc', ' Rwanda', 'Fr'),
       (201, 'USD', 'United States dollar[H]', ' Saba', '$'),
       (202, 'DZD', 'Algerian dinar', ' Sahrawi Republic[N]', ''),
       (203, 'MRU', 'Mauritanian ouguiya', ' Sahrawi Republic[N]', 'UM'),
       (204, 'MAD', 'Moroccan dirham', ' Sahrawi Republic[N]', ''),
       (205, '', 'Sahrawi peseta', ' Sahrawi Republic[N]', 'Ptas'),
       (206, 'SHP', 'Saint Helena pound', ' Saint Helena', ''),
       (207, 'XCD', 'Eastern Caribbean dollar', ' Saint Kitts and Nevis', '$'),
       (208, 'XCD', 'Eastern Caribbean dollar', ' Saint Lucia', '$'),
       (209, 'XCD', 'Eastern Caribbean dollar', ' Saint Vincent and the Grenadines', '$'),
       (210, 'WST', 'Samoan t?l?', ' Samoa', 'T'),
       (211, 'EUR', 'Euro', ' San Marino', '€'),
       (212, 'STN', 'S?o Tomé and Príncipe dobra', ' S?o Tomé and Príncipe', 'Db'),
       (213, 'SAR', 'Saudi riyal', ' Saudi Arabia', ''),
       (214, 'XOF', 'West African CFA franc', ' Senegal', 'Fr'),
       (215, 'RSD', 'Serbian dinar', ' Serbia', 'din.'),
       (216, 'SCR', 'Seychellois rupee', ' Seychelles', ''),
       (217, 'SLL', 'Sierra Leonean leone', ' Sierra Leone', 'Le'),
       (218, 'SGD', 'Singapore dollar', ' Singapore', '$'),
       (219, 'BND', 'Brunei dollar', ' Singapore', '$'),
       (220, 'USD', 'United States dollar[H]', ' Sint Eustatius', '$'),
       (221, 'ANG', 'Netherlands Antillean guilder', ' Sint Maarten', ''),
       (222, 'EUR', 'Euro', ' Slovakia', '€'),
       (223, 'EUR', 'Euro', ' Slovenia', '€'),
       (224, 'SBD', 'Solomon Islands dollar', ' Solomon Islands', '$'),
       (225, 'SOS', 'Somali shilling', ' Somalia', 'Sh'),
       (226, 'SLS[G]', 'Somaliland shilling', ' Somaliland', 'Sl'),
       (227, 'ZAR', 'South African rand', ' South Africa', 'R'),
       (228, 'RUB', 'Russian ruble', ' South Ossetia', ''),
       (229, 'EUR', 'Euro', ' Spain', '€'),
       (230, 'SSP', 'South Sudanese pound', ' South Sudan', ''),
       (231, 'LKR', 'Sri Lankan rupee', ' Sri Lanka', ''),
       (232, 'SDG', 'Sudanese pound', ' Sudan', '?.?.'),
       (233, 'SRD', 'Surinamese dollar', ' Suriname', '$'),
       (234, 'SEK', 'Swedish krona', ' Sweden', 'kr'),
       (235, 'CHF', 'Swiss franc', '  Switzerland', 'Fr.'),
       (236, 'SYP', 'Syrian pound', ' Syria', '? or ?.?'),
       (237, 'TWD', 'New Taiwan dollar', ' Taiwan, Republic of China', '$'),
       (238, 'TJS', 'Tajikistani somoni', ' Tajikistan', '?.'),
       (239, 'TZS', 'Tanzanian shilling', ' Tanzania', 'Sh'),
       (240, 'THB', 'Thai baht', ' Thailand', ''),
       (241, 'XOF', 'West African CFA franc', ' Togo', 'Fr'),
       (242, 'TOP', 'Tongan pa?anga[P]', ' Tonga', 'T$'),
       (243, 'PRB[G]', 'Transnistrian ruble', ' Transnistria', '?.'),
       (244, 'TTD', 'Trinidad and Tobago dollar', ' Trinidad and Tobago', '$'),
       (245, 'TND', 'Tunisian dinar', ' Tunisia', ''),
       (246, 'TRY', 'Turkish lira', ' Turkey', ''),
       (247, 'TMT', 'Turkmenistan manat', ' Turkmenistan', 'm.'),
       (248, 'USD', 'United States dollar', ' Turks and Caicos Islands', '$'),
       (249, 'TVD[G]', 'Tuvaluan dollar', ' Tuvalu', '$'),
       (250, 'AUD', 'Australian dollar', ' Tuvalu', '$'),
       (251, 'UGX', 'Ugandan shilling', ' Uganda', 'USh'),
       (252, 'UAH', 'Ukrainian hryvnia', ' Ukraine', ''),
       (253, 'AED', 'United Arab Emirates dirham', ' United Arab Emirates', ''),
       (254, 'GBP', 'British pound[F]', ' United Kingdom', ''),
       (255, 'USD', 'United States dollar', ' United States', '$'),
       (256, 'UYU', 'Uruguayan peso', ' Uruguay', '$'),
       (257, 'UZS', 'Uzbekistani so?m', ' Uzbekistan', 'S?'),
       (258, 'VUV', 'Vanuatu vatu', ' Vanuatu', 'Vt'),
       (259, 'EUR', 'Euro', '  Vatican City', '€'),
       (260, 'VES', 'Venezuelan bolívar soberano', ' Venezuela', 'Bs.S. or Bs.'),
       (261, 'VED', 'Venezuelan bolívar digital', ' Venezuela', 'Bs.'),
       (262, 'VND', 'Vietnamese đ?ng', ' Vietnam', ''),
       (263, 'XPF', 'CFP franc', ' Wallis and Futuna', ''),
       (264, 'YER', 'Yemeni rial', ' Yemen', ''),
       (265, 'ZMW', 'Zambian kwacha', ' Zambia', 'ZK'),
       (266, 'ZWB[G]', 'RTGS dollar[6]', ' Zimbabwe', 'RTGS$');

